# Generated by Django 5.2.1 on 2025-06-12 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataFinal',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 12, 0, 26, 27, 976216, tzinfo=datetime.timezone.utc), help_text='Informe a data final'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 12, 0, 26, 27, 976216, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial'),
        ),
    ]
