# Generated by Django 5.2.1 on 2025-06-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='numero da Turma', primary_key=True, serialize=False)),
                ('horarioAula', models.TimeField(help_text='Informe horarioAula da Turma')),
                ('duracoaAula', models.SmallIntegerField(help_text='Informe nome do Aluno')),
                ('dataInicial', models.DateField(help_text='Informe data inicial')),
                ('dataFinal', models.TimeField(help_text='Informe data final')),
            ],
        ),
    ]
