# Generated by Django 5.2.1 on 2025-06-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='duracoaAula',
            field=models.SmallIntegerField(help_text='Informe duração'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='horarioAula',
            field=models.TimeField(help_text='Informe horarioAula da aula'),
        ),
    ]
