# Generated by Django 5.2.1 on 2025-06-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_alter_turma_duracoaaula_alter_turma_horarioaula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='dataFinal',
            field=models.DateField(help_text='Informe data final'),
        ),
    ]
